# silly-collections .travis.yml

language: java

jdk:
    - openjdk8

addons:
    apt:
        update: true

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always 
               
after_success:
  - mvn -Pcoveralls -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean test cobertura:cobertura jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report