# silly-collections .travis.yml

language: java

jdk:
    - openjdk8

addons:
    apt:
        update: true

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always 
               
script:
    - mvn test jacoco:report
after_success:
  - mvn coveralls:report