# silly-collections .travis.yml

language: java

cache:
  directories:
    - '$HOME/.m2/repository'
  
jdk:
    - openjdk8

addons:
    apt:
        update: true

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always 
               
script:
    - mvn test cobertura:cobertura
after_success:
    - mvn coveralls:report