# silly-collections .travis.yml

language: java

jdk:
    - openjdk8

addons:
    apt:
        update: true

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always 

after_success:
    - bash <(curl -s https://codecov.io/bash)